services:
    nathiss_quote_generator.twig.extension:
        class: Nathiss\Bundle\QuoteGeneratorBundle\Twig\Extension\NathissQuoteGeneratorExtension
        tags:
            - { name: twig.extension }
        arguments: ['@service_container']
