services:
    nathiss_quote_generator.twig.extension:
        class: %nathiss_quote_generator.twig.extension.class%
        tags:
            - { name: twig.extension }
        arguments: ['@doctrine.orm.entity_manager']
